# Generated by Django 3.0.3 on 2020-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='murid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=30)),
                ('Alamat', models.CharField(max_length=30)),
                ('Nilai', models.FloatField()),
            ],
        ),
    ]
